kind = "mobile"
previewPath = "/nelson-labs-mobile/"
title = "Nelson Labs Mobile"
version = "1.0.0"
id = "artifacts/nelson-labs-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/nelson-labs-mobile/" ]
localPort = 23621

[services.development]
run = "pnpm --filter @workspace/nelson-labs-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nelson-labs-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/nelson-labs-mobile", "run", "serve" ]

[services.env]
PORT = "23621"
BASE_PATH = "/nelson-labs-mobile/"
